import logo from "../../public/assets/images/logo.svg";
import location from "../../public/assets/icon/location.png";
import rupees from "../../public/assets/icon/rupees.png";
import search from "../../public/assets/icon/search.png";
import user from "../../public/assets/icon/user.png";
import video from "../../public/assets/video/hero bg.mp4";
import slide1 from "../../public/assets/images/slider/01.avif";
import slide2 from "../../public/assets/images/slider/02.avif";
import slide3 from "../../public/assets/images/slider/03.avif";
import slide4 from "../../public/assets/images/slider/04.avif";
import edition from "../../public/assets/video/edition.mp4";
import warranty from "../../public/assets/images/warranty.avif";

export const Logo = logo;
export const Location = location;
export const Rupees = rupees;
export const Search = search;
export const User = user;
export const Video = video;
export const Slide1 = slide1;
export const Slide2 = slide2;
export const Slide3 = slide3;
export const Slide4 = slide4;
export const Edition_video = edition;
export const Warranty = warranty;
