import logo from "../../public/assets/images/logo.svg";
import location from "../../public/assets/icon/location.png";
import rupees from "../../public/assets/icon/rupees.png";
import search from "../../public/assets/icon/search.png";
import user from "../../public/assets/icon/user.png";
import video from "../../public/assets/video/hero bg.mp4";
import slide1 from "../../public/assets/images/slider/01.avif";
import slide2 from "../../public/assets/images/slider/02.avif";
import slide3 from "../../public/assets/images/slider/03.avif";
import slide4 from "../../public/assets/images/slider/04.avif";
import edition from "../../public/assets/video/edition.mp4";
import warranty from "../../public/assets/images/warranty.avif";
import watches1 from "../../public/assets/images/watches/01.avif";
import watches2 from "../../public/assets/images/watches/02.avif";
import watches3 from "../../public/assets/images/watches/03.avif";
import watches4 from "../../public/assets/images/watches/04.avif";
import watches5 from "../../public/assets/images/watches/05.avif";
import watches6 from "../../public/assets/images/watches/06.avif";
import watches7 from "../../public/assets/images/watches/07.avif";
import watches8 from "../../public/assets/images/watches/08.avif";
import watches9 from "../../public/assets/images/watches/09.avif";
import watches10 from "../../public/assets/images/watches/10.avif";
import watches11 from "../../public/assets/images/watches/11.avif";
import watches12 from "../../public/assets/images/watches/12.avif";
import chronograph from "../../public/assets/images/chronograph.avif";
import skeleton from "../../public/assets/images/skeleton.avif";
import lether from "../../public/assets/images/lether.avif";
import men from "../../public/assets/images/men.avif";
import women from "../../public/assets/images/women.webp";

export const Logo = logo;
export const Location = location;
export const Rupees = rupees;
export const Search = search;
export const User = user;
export const Video = video;
export const Slide1 = slide1;
export const Slide2 = slide2;
export const Slide3 = slide3;
export const Slide4 = slide4;
export const Edition_video = edition;
export const Warranty = warranty;
export const Watches1 = watches1;
export const Watches2 = watches2;
export const Watches3 = watches3;
export const Watches4 = watches4;
export const Watches5 = watches5;
export const Watches6 = watches6;
export const Watches7 = watches7;
export const Watches8 = watches8;
export const Watches9 = watches9;
export const Watches10 = watches10;
export const Watches11 = watches11;
export const Watches12 = watches12;
export const Chronograph = chronograph;
export const Skeleton = skeleton;
export const Lether = lether;
export const Men = men;
export const Women = women;
